---@meta edgetx

--- AUTO-GENERATED BY edgetx-lua-gen (https://github.com/JeffreyChix/edgetx-lua-gen) — DO NOT EDIT MANUALLY.
--- EdgeTX Lua API stubs for lua-language-server (LuaLS)
--- lcd.* LCD drawing functions

---@class (exact) lcdLib
lcd = {}

--- Refresh the LCD screen
--- 
--- From 2.4.0 on color LCDs, this is done automatically when the screen
--- needs to be refreshed (on events and depending on refresh period).
---
function lcd.refresh() end
--- Clear the LCD screen
---
--- **Since:** 2.0.0
---@param color? number #(optional, only on color screens)
function lcd.clear(color) end
--- Reset the backlight timeout
---
--- **Since:** 2.3.6
function lcd.resetBacklightTimeout() end
--- Draw a single pixel at (x,y) position
---
--- **Since:** 2.0.0
--- > **Notice:** Taranis has an LCD display width of 212 pixels and height of 64 pixels.
--- > Position (0,0) is at top left. Y axis is negative, top line is 0,
--- > bottom line is 63. Drawing on an existing black pixel produces white pixel (TODO check this!)
---@param x number #(positive number) x position
---@param y number #(positive number) y position
---@param flags? number #(optional) please see [Lcd functions overview](../lcd-functions-less-than-greater-than-luadoc-begin-lcd/lcd_functions-overview.html)
function lcd.drawPoint(x, y, flags) end
--- Draw a straight line on LCD
---
--- **Since:** 2.0.0
--- > **Notice:** If the start or the end of the line is outside the LCD dimensions, then the
--- > whole line will not be drawn (starting from OpenTX 2.1.5)
---@param x1 number #(positive numbers) starting coordinate
---@param y1 number #(positive numbers) starting coordinate
---@param x2 number #(positive numbers) end coordinate
---@param y2 number #(positive numbers) end coordinate
---@param pattern number #SOLID or DOTTED
---@param flags? number #(optional) lcdflags
function lcd.drawLine(x1, y1, x2, y2, pattern, flags) end
--- Draw a text beginning at (x,y)
---
--- **Since:** 2.0.0
---@param x number #(positive numbers) starting coordinate
---@param y number #(positive numbers) starting coordinate
---@param text string #(string) text to display
---@param flags? number #(optional) please see [Lcd functions overview](../lcd-functions-less-than-greater-than-luadoc-begin-lcd/lcd_functions-overview.html) for drawing flags and colors, and [Appendix](../../part_vii_-_appendix/fonts.md) for available characters in each font set.
---@param inversColor? number|string #(optional with the INVERS flag) overrides the inverse text color for INVERS
function lcd.drawText(x, y, text, flags, inversColor) end
--- Get the width and height of a text string drawn with flags
---
--- **Since:** 2.5.0
---@param text string #(string)
---@param flags? number #(optional) please see [Lcd functions overview](../lcd-functions-less-than-greater-than-luadoc-begin-lcd/lcd_functions-overview.html)
---@return number w #(integers) width and height of the text
---@return number h #(integers) width and height of the text
function lcd.sizeText(text, flags) end
--- Draw text inside rectangle (x,y,w,h) with line breaks
---
--- **Since:** 2.5.0
---@param x number #(positive numbers) starting coordinate
---@param y number #(positive numbers) starting coordinate
---@param w number #(positive numbers) width and height of bounding rectangle
---@param h number #(positive numbers) width and height of bounding rectangle
---@param text string #(string) text to display
---@param flags? number #(optional) please see [Lcd functions overview](../lcd-functions-less-than-greater-than-luadoc-begin-lcd/lcd_functions-overview.html) for drawing flags and colors, and [Appendix](../../part_vii_-_appendix/fonts.md) for available characters in each font set. RIGHT, CENTER and VCENTER are not implemented.
function lcd.drawTextLines(x, y, w, h, text, flags) end
--- Display a value formatted as time at (x,y)
---
--- **Since:** 2.0.0
---@param x number #(positive numbers) starting coordinate
---@param y number #(positive numbers) starting coordinate
---@param value number #(number) time in seconds
---@param flags? number #(optional) please see [Lcd functions overview](../lcd-functions-less-than-greater-than-luadoc-begin-lcd/lcd_functions-overview.html)
---@param inversColor? number|string #(optional with INVERS flag) overrides the inverse text color for INVERS
function lcd.drawTimer(x, y, value, flags, inversColor) end
--- Display a number at (x,y)
---
--- **Since:** 2.0.0
---@param x number #(positive numbers) starting coordinate
---@param y number #(positive numbers) starting coordinate
---@param value number #(number) value to display
---@param flags? number #(optional) please see [Lcd functions overview](../lcd-functions-less-than-greater-than-luadoc-begin-lcd/lcd_functions-overview.html)
---@param inversColor? number|string #(optional with INVERS flag) overrides the inverse text color for INVERS
function lcd.drawNumber(x, y, value, flags, inversColor) end
--- Display a telemetry value at (x,y)
---
--- **Since:** 2.0.6
---@param x number #(positive numbers) starting coordinate
---@param y number #(positive numbers) starting coordinate
---@param source number|string #can be a source identifier (number) or a source name (string).
--- See getValue()
---@param flags? number #(optional) please see [Lcd functions overview](../lcd-functions-less-than-greater-than-luadoc-begin-lcd/lcd_functions-overview.html)
function lcd.drawChannel(x, y, source, flags) end
--- Draw a text representation of switch at (x,y)
---
--- **Since:** 2.0.0
---@param x number #(positive numbers) starting coordinate
---@param y number #(positive numbers) starting coordinate
---@param switch number #number of switch to display, negative number
--- displays negated switch
---@param flags? number #(optional) please see [Lcd functions overview](../lcd-functions-less-than-greater-than-luadoc-begin-lcd/lcd_functions-overview.html), only SMLSIZE, BLINK and INVERS.
function lcd.drawSwitch(x, y, switch, flags) end
--- Displays the name of the corresponding input as defined by the source at (x,y)
---
--- **Since:** 2.0.0
---@param x number #(positive numbers) starting coordinate
---@param y number #(positive numbers) starting coordinate
---@param source number #source index
---@param flags? number #(optional) please see [Lcd functions overview](../lcd-functions-less-than-greater-than-luadoc-begin-lcd/lcd_functions-overview.html)
function lcd.drawSource(x, y, source, flags) end
--- Displays a bitmap at (x,y)
---
--- **Since:** 2.2.0
--- > **Notice:** Only available on Horus
---@param bitmap any #(pointer) point to a bitmap previously opened with Bitmap.open()
---@param x number #(positive numbers) starting coordinates
---@param y number #(positive numbers) starting coordinates
---@param scale? number #(positive numbers) scale in %, 50 divides size by two, 100 is unchanged, 200 doubles size.
--- Omitting scale draws image in 1:1 scale and is faster than specifying 100 for scale.
function lcd.drawBitmap(bitmap, x, y, scale) end
--- Displays a bitmap pattern at (x,y)
---
--- **Since:** 2.8.0
--- > **Notice:** Only available on Horus
---@param bitmap any #(pointer) point to a bitmap previously opened with Bitmap.open()
---@param x number #(positive numbers) starting coordinates
---@param y number #(positive numbers) starting coordinates
---@param flags? number #(optional) please see [Lcd functions overview](../lcd-functions-less-than-greater-than-luadoc-begin-lcd/lcd_functions-overview.html)
function lcd.drawBitmapPattern(bitmap, x, y, flags) end
--- Displays a bitmap pattern pie at (x,y)
---
--- **Since:** 2.8.0
--- > **Notice:** Only available on Horus
---@param bitmap any #(pointer) point to a bitmap previously opened with Bitmap.open()
---@param x number #(positive numbers) starting coordinates
---@param y number #(positive numbers) starting coordinates
---@param startAngle any #Start angle
---@param endAngle any #End angle
---@param flags? number #(optional) please see [Lcd functions overview](../lcd-functions-less-than-greater-than-luadoc-begin-lcd/lcd_functions-overview.html)
function lcd.drawBitmapPatternPie(bitmap, x, y, startAngle, endAngle, flags) end
--- Draw a rectangle from top left corner (x,y) of specified width and height
---
--- **Since:** 2.0.0
---@param x number #(positive numbers) top left corner position
---@param y number #(positive numbers) top left corner position
---@param w number #(number) width in pixels
---@param h number #(number) height in pixels
---@param flags? number #(optional) please see [Lcd functions overview](../lcd-functions-less-than-greater-than-luadoc-begin-lcd/lcd_functions-overview.html)
---@param t? number #thickness in pixels, defaults to 1 (only on Horus)
---@param opacity? number #opacity defaults to 0 (only on Horus)
function lcd.drawRectangle(x, y, w, h, flags, t, opacity) end
--- Draw a solid rectangle from top left corner (x,y) of specified width and height
---
--- **Since:** 2.0.0
---@param x number #(positive numbers) top left corner position
---@param y number #(positive numbers) top left corner position
---@param w number #(number) width in pixels
---@param h number #(number) height in pixels
---@param flags? number #(optional) please see [Lcd functions overview](../lcd-functions-less-than-greater-than-luadoc-begin-lcd/lcd_functions-overview.html)
---@param opacity? number #opacity defaults to 0 (only on Horus)
function lcd.drawFilledRectangle(x, y, w, h, flags, opacity) end
--- Invert a rectangle zone from top left corner (x,y) of specified width and height
---
--- **Since:** 2.8.0
---@param x number #(positive numbers) top left corner position
---@param y number #(positive numbers) top left corner position
---@param w number #(number) width in pixels
---@param h number #(number) height in pixels
---@param flags? number #(optional) please see [Lcd functions overview](../lcd-functions-less-than-greater-than-luadoc-begin-lcd/lcd_functions-overview.html)
function lcd.invertRect(x, y, w, h, flags) end
--- Draw a simple gauge that is filled based upon fill value
---
--- **Since:** 2.0.0
---@param x number #(positive numbers) top left corner position
---@param y number #(positive numbers) top left corner position
---@param w number #(number) width in pixels
---@param h number #(number) height in pixels
---@param fill number #amount of fill to apply
---@param maxfill number #total value of fill
---@param flags? number #(optional) please see [Lcd functions overview](../lcd-functions-less-than-greater-than-luadoc-begin-lcd/lcd_functions-overview.html)
function lcd.drawGauge(x, y, w, h, fill, maxfill, flags) end
--- Change an indexed color (theme colors and CUSTOM_COLOR). Please see [Lcd functions overview](../lcd-functions-less-than-greater-than-luadoc-begin-lcd/lcd_functions-overview.html#color-constants)
--- 
--- Please notice that changing theme colors affects not only other Lua widgets, but the entire radio interface.
---
--- **Since:** 2.2.0
--- > **Notice:** Only available on radios with color display
---@param colorIndex number
---@param color number
function lcd.setColor(colorIndex, color) end
--- Get the color value from flags
---
--- **Since:** 2.3.11
--- > **Notice:** Only available on radios with color display
---@param flags? number #(flags) please see [Lcd functions overview](../lcd-functions-less-than-greater-than-luadoc-begin-lcd/lcd_functions-overview.html)
---@return number color #(flag) only the RGB565 color value of the input
function lcd.getColor(flags) end
--- Returns a drawing flag with RGB color code
---
--- **Since:** 2.2.0
--- > **Notice:** Only available on radios with color display. Use *either* lcd.RGB(r,g,b) *or* lcd.RGB(rgb)
---@param r number #a number between 0 and 255 that expresses the amount of red in the color
---@param g number #a number between 0 and 255 that expresses the amount of green in the color
---@param b number #a number between 0 and 255 that expresses the amount of blue in the color
---@overload fun(rgb: number): number #a number between 0 and 0xFFFFFF that expresses the RGB value (0xFF000=RED, 0x00FF00=GREEN, 0x0000FF=BLUE)
---@return number flag #with RGB565 color
function lcd.RGB(r, g, b) end
--- Draw a circle at (x, y) of specified radius
---
--- **Since:** 2.4.0
---@param x number #(positive numbers) center position
---@param y number #(positive numbers) center position
---@param r number #radius in pixels
---@param flags? number #(optional) please see [Lcd functions overview](../lcd-functions-less-than-greater-than-luadoc-begin-lcd/lcd_functions-overview.html)
function lcd.drawCircle(x, y, r, flags) end
--- Draw a filled circle at (x, y) of specified radius
---
--- **Since:** 2.4.0
---@param x number #(positive numbers) center position
---@param y number #(positive numbers) center position
---@param r number #radius in pixels
---@param flags? number #(optional) please see [Lcd functions overview](../lcd-functions-less-than-greater-than-luadoc-begin-lcd/lcd_functions-overview.html)
function lcd.drawFilledCircle(x, y, r, flags) end
--- Draw a triangle
---
--- **Since:** 2.4.0
---@param x1 number #(positive numbers) coordinates of the three vertices
---@param y1 number #(positive numbers) coordinates of the three vertices
---@param x2 number #(positive numbers) coordinates of the three vertices
---@param y2 number #(positive numbers) coordinates of the three vertices
---@param x3 number #(positive numbers) coordinates of the three vertices
---@param y3 number #(positive numbers) coordinates of the three vertices
---@param flags? number #(optional) please see [Lcd functions overview](../lcd-functions-less-than-greater-than-luadoc-begin-lcd/lcd_functions-overview.html)
function lcd.drawTriangle(x1, y1, x2, y2, x3, y3, flags) end
--- Draw a filled triangle
---
--- **Since:** 2.4.0
---@param x1 number #(positive numbers) coordinates of the three vertices
---@param y1 number #(positive numbers) coordinates of the three vertices
---@param x2 number #(positive numbers) coordinates of the three vertices
---@param y2 number #(positive numbers) coordinates of the three vertices
---@param x3 number #(positive numbers) coordinates of the three vertices
---@param y3 number #(positive numbers) coordinates of the three vertices
---@param flags? number #(optional) please see [Lcd functions overview](../lcd-functions-less-than-greater-than-luadoc-begin-lcd/lcd_functions-overview.html)
function lcd.drawFilledTriangle(x1, y1, x2, y2, x3, y3, flags) end
--- Draw an arc
---
--- **Since:** 2.4.0
---@param x number #(positive numbers) coordinates of the center
---@param y number #(positive numbers) coordinates of the center
---@param r number #(positive number) radius
---@param start number #(positive numbers) start and end of the arc
---@param _end number #(positive numbers) start and end of the arc
---@param flags? number #(optional) please see [Lcd functions overview](../lcd-functions-less-than-greater-than-luadoc-begin-lcd/lcd_functions-overview.html)
function lcd.drawArc(x, y, r, start, _end, flags) end
--- Draw a pie slice
---
--- **Since:** 2.4.0
---@param x number #(positive numbers) coordinates of the center
---@param y number #(positive numbers) coordinates of the center
---@param r number #(positive number) radius
---@param start number #(positive numbers) start and end of the pie slice
---@param _end number #(positive numbers) start and end of the pie slice
---@param flags? number #(optional) please see [Lcd functions overview](../lcd-functions-less-than-greater-than-luadoc-begin-lcd/lcd_functions-overview.html)
function lcd.drawPie(x, y, r, start, _end, flags) end
--- Draw an arc
---
--- **Since:** 2.4.0
---@param x number #(positive numbers) coordinates of the center
---@param y number #(positive numbers) coordinates of the center
---@param r1 number #(positive numbers) radii of the inside and outside of the annulus
---@param r2 number #(positive numbers) radii of the inside and outside of the annulus
---@param start number #(positive numbers) start and end of the annulus
---@param _end number #(positive numbers) start and end of the annulus
---@param flags? number #(optional) please see [Lcd functions overview](../lcd-functions-less-than-greater-than-luadoc-begin-lcd/lcd_functions-overview.html)
function lcd.drawAnnulus(x, y, r1, r2, start, _end, flags) end
--- Draw a line only inside a rectangle
---
--- **Since:** 2.4.0
---@param x1 number #(positive numbers) coordinates of the start and end of the unclipped line
---@param y1 number #(positive numbers) coordinates of the start and end of the unclipped line
---@param x2 number #(positive numbers) coordinates of the start and end of the unclipped line
---@param y2 any
---@param xmin number #(positive numbers) the limits of the rectangle inside which the line is drawn
---@param xmax number #(positive numbers) the limits of the rectangle inside which the line is drawn
---@param ymin number #(positive numbers) the limits of the rectangle inside which the line is drawn
---@param ymax number #(positive numbers) the limits of the rectangle inside which the line is drawn
---@param pattern number #(FORCE, ERASE, DOTTED) please see [Lcd functions overview](../lcd-functions-less-than-greater-than-luadoc-begin-lcd/lcd_functions-overview.html)
---@param flags? number #(optional) please see [Lcd functions overview](../lcd-functions-less-than-greater-than-luadoc-begin-lcd/lcd_functions-overview.html)
function lcd.drawLineWithClipping(x1, y1, x2, y2, xmin, xmax, ymin, ymax, pattern, flags) end
--- Draw a rectangle in perspective
---
--- **Since:** 2.4.0
---@param pitch number #(positive numbers) pitch and roll to define the orientation of the rectangle
---@param roll number #(positive numbers) pitch and roll to define the orientation of the rectangle
---@param xmin number #(positive numbers) the limits of the rectangle
---@param xmax number #(positive numbers) the limits of the rectangle
---@param ymin number #(positive numbers) the limits of the rectangle
---@param ymax number #(positive numbers) the limits of the rectangle
---@param flags? number #(optional) please see [Lcd functions overview](../lcd-functions-less-than-greater-than-luadoc-begin-lcd/lcd_functions-overview.html)
function lcd.drawHudRectangle(pitch, roll, xmin, xmax, ymin, ymax, flags) end
--- Exit full screen widget mode.
---
--- **Since:** 2.5.0
--- > **Notice:** Only available on radios with color display
function lcd.exitFullScreen() end
--- Returns the rightmost x position from previous output
---
--- **Since:** 2.0.0
--- > **Notice:** Only available on Taranis
--- > **Notice:** For added clarity, it is recommended to use lcd.getLastRightPos()
---@return number number #(integer) x position
function lcd.getLastPos() end
--- Returns the rightest x position from previous drawtext or drawNumber output
---
--- **Since:** 2.2.0
--- > **Notice:** Only available on Taranis
--- > **Notice:** This is strictly equivalent to former lcd.getLastPos()
---@return number number #(integer) x position
function lcd.getLastRightPos() end
--- Returns the leftmost x position from previous drawtext or drawNumber output
---
--- **Since:** 2.2.0
--- > **Notice:** Only available on Taranis
---@return number number #(integer) x position
function lcd.getLastLeftPos() end
--- Draw a bitmap at (x,y)
---
--- **Since:** 2.0.0
--- > **Notice:** Maximum image size is [display width / 2] x [display height] pixels.
---@param x number #(positive numbers) starting coordinates
---@param y number #(positive numbers) starting coordinates
---@param name string #(string) full path to the bitmap on SD card (i.e. “/IMAGES/test.bmp”)
function lcd.drawPixmap(x, y, name) end
--- Draw a title bar
---
--- **Since:** 2.0.0
--- > **Notice:** Only available on Taranis
---@param title string #(string) text for the title
---@param page number #page number
---@param pages number #total number of pages. Only used as indicator on
--- the right side of title bar. (i.e. idx=2, cnt=5, display `2/5`)
function lcd.drawScreenTitle(title, page, pages) end
--- Draw a combo box
---
--- **Since:** 2.0.0
--- > **Notice:** Only available on Taranis
---@param x number #(positive numbers) top left corner position
---@param y number #(positive numbers) top left corner position
---@param w number #(number) width of combo box in pixels
---@param list table #combo box elements, each element is a string
---@param idx number #(integer) index of entry to highlight
---@param flags? number #(unsigned number) drawing flags, the flags can not be combined:
--- `BLINK` combo box is expanded
--- `INVERS` combo box collapsed, text inversed
--- `0 or not present` combo box collapsed, text normal
function lcd.drawCombobox(x, y, w, list, idx, flags) end
