---@meta edgetx

--- AUTO-GENERATED BY edgetx-lua-gen (https://github.com/JeffreyChix/edgetx-lua-gen) — DO NOT EDIT MANUALLY.
--- EdgeTX Lua API stubs for lua-language-server (LuaLS)
--- Bitmap.* bitmap manipulation functions

---@class (exact) BitmapLib
Bitmap = {}

--- Loads a bitmap in memory, for later use with lcd.drawBitmap(). Bitmaps should be loaded only
--- once, returned object should be stored and used for drawing. If loading fails for whatever
--- reason the resulting bitmap object will have width and height set to zero.
--- 
--- Bitmap loading can fail if:
--- File is not found or contains invalid image
--- System is low on memory
--- Combined memory usage of all Lua script bitmaps exceeds certain value
---
--- **Since:** 2.2.0
--- > **Notice:** Only available on Horus
---@param name string #(string) full path to the bitmap on SD card (i.e. “/IMAGES/test.bmp”)
---@return any bitmap #(object) a bitmap object that can be used with other bitmap functions
function Bitmap.open(name) end
--- Return width, height of a bitmap object
---
--- **Since:** 2.2.0
--- > **Notice:** Only available on Horus
---@param name string
---@param bitmap? any #(pointer) point to a bitmap previously opened with Bitmap.open()
---@return number multiple #returns 2 values:
--- (number) width in pixels
--- (number) height in pixels
function Bitmap.getSize(name, bitmap) end
--- Return a resized bitmap object
---
--- **Since:** 2.8.0
--- > **Notice:** Only available on Horus
---@param bitmap any #(pointer) point to a bitmap previously opened with Bitmap.open()
---@param width number #(number) the new bitmap width
---@param height number #(number) the new bitmap height
function Bitmap.resize(bitmap, width, height) end
--- Return a 8bit bitmap mask that can be used with lcd.drawBitmapPattern()
---
--- **Since:** 2.8.0
--- > **Notice:** Only available on Horus
---@param bitmap any #(pointer) point to a bitmap previously opened with Bitmap.open()
---@return any a #bitmap mask
function Bitmap.toMask(bitmap) end
