/**
 * TX15-adapted modular Betaflight / CRSF quad sections.
 *
 * Information architecture drawn from common color-radio FPV dashboards
 * (top bar, dual bars, voltage/timer heroes, metric grids, GPS row) and
 * whoop-style armed banners — reimplemented as direct lcd.* blocks for
 * preview + editor (no bitmaps, no person/repo branding).
 */

import type { PrefabSection } from "./types.ts";

export const BETAFLIGHT_QUAD_PREFABS: PrefabSection[] = [
  {
    id: "quad-armed-banner",
    label: "Armed banner",
    shortLabel: "ARM",
    description:
      "Whoop-style full-width armed / disarmed banner with link readout",
    family: "betaflight-quad",
    protocol: "betaflight",
    category: "header",
    requiredSensors: ["FM"],
    optionalSensors: ["RQLY"],
    telemetryNotes: [
      "Uses FM string — trailing '*' or missing ARM usually means disarmed (Betaflight CRSF).",
      "Orange fill when armed; grey when safe.",
    ],
    createSrcBindings: {
      fm: "FM",
      rqly: "RQLY",
    },
    srcSlotLabels: {
      fm: "Flight mode",
      rqly: "Link quality",
    },
    defaultBounds: { x: 0, y: 0, w: 480, h: 36 },
    refreshLines: [
      "local fmRaw = widget.src.fm and getValue(widget.src.fm) or nil",
      'local fmStr = type(fmRaw) == "string" and fmRaw or ""',
      'local armed = string.find(string.upper(fmStr), "ARM") ~= nil and string.sub(fmStr, -1) ~= "*"',
      "local rqly = telem(widget.src.rqly)",
      'local rqlyStr = tostring(math.floor(rqly + 0.5)) .. "%"',
      "if armed then",
      "  lcd.drawFilledRectangle(0, 0, 480, 36, ORANGE)",
      '  lcd.drawText(12, 10, "ARMED", MIDSIZE + BLACK)',
      "else",
      "  lcd.drawFilledRectangle(0, 0, 480, 36, GREY)",
      '  lcd.drawText(12, 10, "WHOOP", MIDSIZE + WHITE)',
      "end",
      "lcd.drawText(420, 12, rqlyStr, SMLSIZE + GREEN)",
    ],
  },
  {
    id: "quad-topbar",
    label: "Quad top bar",
    shortLabel: "TB",
    description: "Title bar with optional ARM / SAFE chip and link percent",
    family: "betaflight-quad",
    protocol: "any",
    category: "header",
    requiredSensors: ["RQLY"],
    optionalSensors: ["FM"],
    telemetryNotes: [
      "Generic header for freestyle / dense boards. Bind FM for arm chip.",
    ],
    createSrcBindings: {
      rqly: "RQLY",
      fm: "FM",
    },
    srcSlotLabels: {
      rqly: "Link quality",
      fm: "Flight mode",
    },
    defaultBounds: { x: 0, y: 0, w: 480, h: 40 },
    refreshLines: [
      "local rqly = telem(widget.src.rqly)",
      'local rqlyStr = tostring(math.floor(rqly + 0.5)) .. "%"',
      "local fmRaw = widget.src.fm and getValue(widget.src.fm) or nil",
      'local fmStr = type(fmRaw) == "string" and fmRaw or ""',
      'local armed = string.find(string.upper(fmStr), "ARM") ~= nil and string.sub(fmStr, -1) ~= "*"',
      "lcd.drawFilledRectangle(0, 0, 480, 40, GREY)",
      'lcd.drawText(12, 12, "QUAD", MIDSIZE + WHITE)',
      "if armed then",
      "  lcd.drawFilledRectangle(396, 8, 60, 24, ORANGE)",
      '  lcd.drawText(408, 12, "ARM", SMLSIZE + BLACK)',
      "else",
      '  lcd.drawText(412, 14, "SAFE", SMLSIZE + GREEN)',
      "end",
      "lcd.drawText(340, 14, rqlyStr, SMLSIZE + GREEN)",
    ],
  },
  {
    id: "quad-link-batt-bars",
    label: "Link + battery bars",
    shortLabel: "BARS",
    description: "Stacked link-quality and pack-voltage progress bars",
    family: "betaflight-quad",
    protocol: "any",
    category: "strip",
    requiredSensors: ["RQLY", "RxBt"],
    optionalSensors: [],
    telemetryNotes: [
      "Battery fill estimates from RxBt assuming ~3.3–4.2 V/cell on a 1S–6S pack guess.",
    ],
    createSrcBindings: {
      rqly: "RQLY",
      rxbt: "RxBt",
    },
    srcSlotLabels: {
      rqly: "Link quality",
      rxbt: "Pack voltage",
    },
    defaultBounds: { x: 12, y: 48, w: 456, h: 72 },
    refreshLines: [
      "local rqly = telem(widget.src.rqly)",
      "local volts = telem(widget.src.rxbt)",
      "local cells = 1",
      "if volts > 17 then cells = 6 elseif volts > 13.5 then cells = 4 elseif volts > 10 then cells = 3 elseif volts > 6.5 then cells = 2 end",
      "local cellV = cells > 0 and (volts / cells) or 0",
      "local battPct = math.max(0, math.min(100, (cellV - 3.3) / (4.2 - 3.3) * 100))",
      'lcd.drawText(12, 48, "LINK", SMLSIZE + GREY)',
      "lcd.drawFilledRectangle(12, 64, 456, 12, GREY)",
      "local linkFill = math.floor(452 * math.max(0, math.min(100, rqly)) / 100)",
      "if linkFill > 0 then lcd.drawFilledRectangle(14, 66, linkFill, 8, GREEN) end",
      'lcd.drawText(12, 88, "BATT", SMLSIZE + GREY)',
      "lcd.drawFilledRectangle(12, 104, 456, 12, GREY)",
      "local battFill = math.floor(452 * battPct / 100)",
      "if battFill > 0 then lcd.drawFilledRectangle(14, 106, battFill, 8, YELLOW) end",
    ],
  },
  {
    id: "quad-voltage-hero",
    label: "Voltage hero card",
    shortLabel: "V",
    description: "Large pack voltage card with current secondary",
    family: "betaflight-quad",
    protocol: "any",
    category: "hero",
    requiredSensors: ["RxBt"],
    optionalSensors: ["Curr"],
    telemetryNotes: ["Hero voltage for whoop / pack-focused layouts."],
    createSrcBindings: {
      rxbt: "RxBt",
      curr: "Curr",
    },
    srcSlotLabels: {
      rxbt: "Pack voltage",
      curr: "Current",
    },
    defaultBounds: { x: 12, y: 132, w: 222, h: 100 },
    refreshLines: [
      "local volts = telem(widget.src.rxbt)",
      "local amps = telem(widget.src.curr)",
      'local vStr = string.format("%.2f", volts)',
      'local aStr = string.format("%.1fA", amps)',
      "lcd.drawFilledRectangle(12, 132, 222, 100, DARKGREY)",
      "lcd.drawRectangle(12, 132, 222, 100, GREY)",
      'lcd.drawText(20, 140, "VOLTAGE", SMLSIZE + GREY)',
      "lcd.drawText(20, 160, vStr, DBLSIZE + YELLOW)",
      "lcd.drawText(20, 204, aStr, MIDSIZE + WHITE)",
    ],
  },
  {
    id: "quad-attitude-card",
    label: "Attitude card",
    shortLabel: "ATT",
    description: "Pitch / roll readout card",
    family: "betaflight-quad",
    protocol: "any",
    category: "card",
    requiredSensors: ["Ptch", "Roll"],
    optionalSensors: [],
    telemetryNotes: [
      "Needs attitude telemetry (Ptch / Roll) from the flight controller via CRSF.",
    ],
    createSrcBindings: {
      pitch: "Ptch",
      roll: "Roll",
    },
    srcSlotLabels: {
      pitch: "Pitch",
      roll: "Roll",
    },
    defaultBounds: { x: 246, y: 132, w: 222, h: 100 },
    refreshLines: [
      "local pitch = telem(widget.src.pitch)",
      "local roll = telem(widget.src.roll)",
      'local pitchStr = string.format("%.0f", pitch)',
      'local rollStr = string.format("%.0f", roll)',
      "lcd.drawFilledRectangle(246, 132, 222, 100, DARKGREY)",
      "lcd.drawRectangle(246, 132, 222, 100, GREY)",
      'lcd.drawText(254, 140, "PITCH / ROLL", SMLSIZE + GREY)',
      "lcd.drawText(254, 164, pitchStr, MIDSIZE + WHITE)",
      "lcd.drawText(254, 192, rollStr, MIDSIZE + WHITE)",
    ],
  },
  {
    id: "quad-timer-hero",
    label: "Timer hero",
    shortLabel: "TMR",
    description: "Large flight-timer hero (model timer 1)",
    family: "betaflight-quad",
    protocol: "any",
    category: "hero",
    requiredSensors: [],
    optionalSensors: [],
    telemetryNotes: [
      "Reads EdgeTX model timer 1. Configure a throttle or switch timer on the model.",
    ],
    createSrcBindings: {},
    defaultBounds: { x: 12, y: 56, w: 220, h: 64 },
    refreshLines: [
      "local t1 = model.getTimer(1)",
      "local tSecs = (t1 and t1.value) and math.floor(math.abs(t1.value)) or 0",
      'local tStr = string.format("%d:%02d", math.floor(tSecs / 60), tSecs % 60)',
      'lcd.drawText(12, 56, "TIMER", SMLSIZE + GREY)',
      "lcd.drawText(12, 76, tStr, DBLSIZE + WHITE)",
    ],
  },
  {
    id: "quad-power-strip",
    label: "Power strip",
    shortLabel: "PWR",
    description: "Three-up pack / current / link strip",
    family: "betaflight-quad",
    protocol: "any",
    category: "strip",
    requiredSensors: ["RxBt", "Curr", "RQLY"],
    optionalSensors: ["1RSS"],
    telemetryNotes: ["Freestyle mid-board strip for pack, current, and link."],
    createSrcBindings: {
      rxbt: "RxBt",
      curr: "Curr",
      rqly: "RQLY",
      rssi: "1RSS",
    },
    srcSlotLabels: {
      rxbt: "Pack voltage",
      curr: "Current",
      rqly: "Link quality",
      rssi: "RSSI",
    },
    defaultBounds: { x: 12, y: 130, w: 456, h: 72 },
    refreshLines: [
      "local volts = telem(widget.src.rxbt)",
      "local amps = telem(widget.src.curr)",
      "local rqly = telem(widget.src.rqly)",
      "local rssi = telem(widget.src.rssi)",
      'local vStr = string.format("%.1fV", volts)',
      'local aStr = string.format("%.1fA", amps)',
      'local rqlyStr = tostring(math.floor(rqly + 0.5)) .. "%"',
      "local rssiStr = tostring(math.floor(rssi + 0.5))",
      "lcd.drawFilledRectangle(12, 130, 144, 72, DARKGREY)",
      "lcd.drawRectangle(12, 130, 144, 72, GREY)",
      'lcd.drawText(20, 138, "PACK", SMLSIZE + GREY)',
      "lcd.drawText(20, 158, vStr, MIDSIZE + YELLOW)",
      "lcd.drawFilledRectangle(168, 130, 144, 72, DARKGREY)",
      "lcd.drawRectangle(168, 130, 144, 72, GREY)",
      'lcd.drawText(176, 138, "CURR", SMLSIZE + GREY)',
      "lcd.drawText(176, 158, aStr, MIDSIZE + BLUE)",
      "lcd.drawFilledRectangle(324, 130, 144, 72, DARKGREY)",
      "lcd.drawRectangle(324, 130, 144, 72, GREY)",
      'lcd.drawText(332, 138, "LINK", SMLSIZE + GREY)',
      "lcd.drawText(332, 158, rqlyStr, MIDSIZE + GREEN)",
      "lcd.drawText(332, 180, rssiStr, SMLSIZE + WHITE)",
    ],
  },
  {
    id: "quad-metric-grid",
    label: "Metric grid 2×3",
    shortLabel: "GRID",
    description: "Dense six-cell telemetry grid (link, power, GPS)",
    family: "betaflight-quad",
    protocol: "any",
    category: "strip",
    requiredSensors: ["RQLY", "RxBt", "Curr"],
    optionalSensors: ["1RSS", "Alt", "GSpd"],
    telemetryNotes: [
      "Color-radio style primary grid: RQLY, 1RSS, VOLT, CURR, ALT, GSPD.",
    ],
    createSrcBindings: {
      rqly: "RQLY",
      rssi: "1RSS",
      rxbt: "RxBt",
      curr: "Curr",
      alt: "Alt",
      gspd: "GSpd",
    },
    srcSlotLabels: {
      rqly: "Link quality",
      rssi: "RSSI",
      rxbt: "Pack voltage",
      curr: "Current",
      alt: "Altitude",
      gspd: "Ground speed",
    },
    defaultBounds: { x: 12, y: 52, w: 456, h: 152 },
    refreshLines: [
      "local rqly = telem(widget.src.rqly)",
      "local rssi = telem(widget.src.rssi)",
      "local volts = telem(widget.src.rxbt)",
      "local amps = telem(widget.src.curr)",
      "local alt = telem(widget.src.alt)",
      "local gspd = telem(widget.src.gspd)",
      'local c1 = tostring(math.floor(rqly + 0.5)) .. "%"',
      "local c2 = tostring(math.floor(rssi + 0.5))",
      'local c3 = string.format("%.1fV", volts)',
      'local c4 = string.format("%.1fA", amps)',
      'local c5 = string.format("%.0fm", alt)',
      'local c6 = string.format("%.0f", gspd)',
      "local cellW = 144",
      "local cellH = 72",
      "local gap = 12",
      "local x0 = 12",
      "local x1 = 12 + cellW + gap",
      "local x2 = 12 + 2 * (cellW + gap)",
      "local y0 = 52",
      "local y1 = 52 + cellH + gap",
      "lcd.drawFilledRectangle(x0, y0, cellW, cellH, DARKGREY)",
      "lcd.drawRectangle(x0, y0, cellW, cellH, GREY)",
      'lcd.drawText(x0 + 8, y0 + 8, "RQLY", SMLSIZE + GREY)',
      "lcd.drawText(x0 + 8, y0 + 28, c1, MIDSIZE + WHITE)",
      "lcd.drawFilledRectangle(x1, y0, cellW, cellH, DARKGREY)",
      "lcd.drawRectangle(x1, y0, cellW, cellH, GREY)",
      'lcd.drawText(x1 + 8, y0 + 8, "1RSS", SMLSIZE + GREY)',
      "lcd.drawText(x1 + 8, y0 + 28, c2, MIDSIZE + WHITE)",
      "lcd.drawFilledRectangle(x2, y0, cellW, cellH, DARKGREY)",
      "lcd.drawRectangle(x2, y0, cellW, cellH, GREY)",
      'lcd.drawText(x2 + 8, y0 + 8, "VOLT", SMLSIZE + GREY)',
      "lcd.drawText(x2 + 8, y0 + 28, c3, MIDSIZE + WHITE)",
      "lcd.drawFilledRectangle(x0, y1, cellW, cellH, DARKGREY)",
      "lcd.drawRectangle(x0, y1, cellW, cellH, GREY)",
      'lcd.drawText(x0 + 8, y1 + 8, "CURR", SMLSIZE + GREY)',
      "lcd.drawText(x0 + 8, y1 + 28, c4, MIDSIZE + WHITE)",
      "lcd.drawFilledRectangle(x1, y1, cellW, cellH, DARKGREY)",
      "lcd.drawRectangle(x1, y1, cellW, cellH, GREY)",
      'lcd.drawText(x1 + 8, y1 + 8, "ALT", SMLSIZE + GREY)',
      "lcd.drawText(x1 + 8, y1 + 28, c5, MIDSIZE + WHITE)",
      "lcd.drawFilledRectangle(x2, y1, cellW, cellH, DARKGREY)",
      "lcd.drawRectangle(x2, y1, cellW, cellH, GREY)",
      'lcd.drawText(x2 + 8, y1 + 8, "GSPD", SMLSIZE + GREY)',
      "lcd.drawText(x2 + 8, y1 + 28, c6, MIDSIZE + WHITE)",
    ],
  },
  {
    id: "quad-gps-row",
    label: "GPS row",
    shortLabel: "GPS",
    description: "Altitude / speed / satellites strip",
    family: "betaflight-quad",
    protocol: "any",
    category: "footer",
    requiredSensors: ["Alt", "GSpd", "Sats"],
    optionalSensors: [],
    telemetryNotes: ["Requires GPS telemetry sensors on the model."],
    createSrcBindings: {
      alt: "Alt",
      gspd: "GSpd",
      sats: "Sats",
    },
    srcSlotLabels: {
      alt: "Altitude",
      gspd: "Ground speed",
      sats: "Satellites",
    },
    defaultBounds: { x: 12, y: 220, w: 456, h: 52 },
    refreshLines: [
      "local alt = telem(widget.src.alt)",
      "local gspd = telem(widget.src.gspd)",
      "local sats = telem(widget.src.sats)",
      'local altStr = string.format("%.0f m", alt)',
      'local spdStr = string.format("%.0f km/h", gspd)',
      "local satsStr = tostring(sats)",
      "lcd.drawFilledRectangle(12, 220, 456, 52, DARKGREY)",
      "lcd.drawRectangle(12, 220, 456, 52, GREY)",
      'lcd.drawText(20, 228, "GPS", SMLSIZE + GREY)',
      "lcd.drawText(20, 246, altStr, MIDSIZE + WHITE)",
      "lcd.drawText(160, 246, spdStr, MIDSIZE + WHITE)",
      "lcd.drawText(320, 246, satsStr, MIDSIZE + BLUE)",
    ],
  },
  {
    id: "quad-capacity-chip",
    label: "Capacity chip",
    shortLabel: "mAh",
    description: "Consumed capacity (Capa) readout",
    family: "betaflight-quad",
    protocol: "any",
    category: "card",
    requiredSensors: ["Capa"],
    optionalSensors: [],
    telemetryNotes: ["Shows Capa sensor when the FC reports mAh used."],
    createSrcBindings: {
      capa: "Capa",
    },
    srcSlotLabels: {
      capa: "Capacity used",
    },
    defaultBounds: { x: 12, y: 244, w: 200, h: 28 },
    refreshLines: [
      "local capa = telem(widget.src.capa)",
      'local capaStr = string.format("%.0f mAh", capa)',
      'lcd.drawText(12, 248, "CAPA", SMLSIZE + GREY)',
      "lcd.drawText(60, 244, capaStr, MIDSIZE + BLUE)",
    ],
  },
  {
    id: "quad-mode-footer",
    label: "Mode footer",
    shortLabel: "FM",
    description: "Footer strip with flight-mode / status text",
    family: "betaflight-quad",
    protocol: "any",
    category: "footer",
    requiredSensors: ["FM"],
    optionalSensors: [],
    telemetryNotes: ["Shows FM string or a Ready fallback."],
    createSrcBindings: {
      fm: "FM",
    },
    srcSlotLabels: {
      fm: "Flight mode",
    },
    defaultBounds: { x: 0, y: 292, w: 480, h: 28 },
    refreshLines: [
      "local fmRaw = widget.src.fm and getValue(widget.src.fm) or nil",
      "lcd.drawFilledRectangle(0, 292, 480, 28, DARKGREY)",
      'if type(fmRaw) == "string" and fmRaw ~= "" then',
      "  lcd.drawText(12, 300, fmRaw, SMLSIZE + ORANGE)",
      "else",
      '  lcd.drawText(12, 300, "Ready", SMLSIZE + GREY)',
      "end",
    ],
  },
  {
    id: "quad-voltage-minimal",
    label: "Minimal voltage hero",
    shortLabel: "V+",
    description: "Open voltage + current stack for minimal boards",
    family: "betaflight-quad",
    protocol: "any",
    category: "hero",
    requiredSensors: ["RxBt"],
    optionalSensors: ["Curr", "Alt"],
    telemetryNotes: ["Used by the minimal-quad board (no card chrome)."],
    createSrcBindings: {
      rxbt: "RxBt",
      curr: "Curr",
      alt: "Alt",
    },
    srcSlotLabels: {
      rxbt: "Pack voltage",
      curr: "Current",
      alt: "Altitude",
    },
    defaultBounds: { x: 12, y: 64, w: 200, h: 100 },
    refreshLines: [
      "local volts = telem(widget.src.rxbt)",
      "local amps = telem(widget.src.curr)",
      "local alt = telem(widget.src.alt)",
      'local vStr = string.format("%.1f", volts)',
      'local aStr = string.format("%.0fA", amps)',
      'local altStr = string.format("%.0fm", alt)',
      'lcd.drawText(12, 64, "PACK", SMLSIZE + GREY)',
      "lcd.drawText(12, 84, vStr, DBLSIZE + YELLOW)",
      'lcd.drawText(132, 100, "V", MIDSIZE + WHITE)',
      "lcd.drawText(12, 140, aStr, MIDSIZE + BLUE)",
      'lcd.drawText(12, 236, "ALT", SMLSIZE + GREY)',
      "lcd.drawText(52, 232, altStr, MIDSIZE + BLUE)",
    ],
  },
  {
    id: "quad-timer-card",
    label: "Timer card",
    shortLabel: "TC",
    description: "Carded flight timer for minimal layouts",
    family: "betaflight-quad",
    protocol: "any",
    category: "card",
    requiredSensors: [],
    optionalSensors: [],
    telemetryNotes: ["Model timer 1 inside a bordered card."],
    createSrcBindings: {},
    defaultBounds: { x: 308, y: 64, w: 148, h: 88 },
    refreshLines: [
      "local t1 = model.getTimer(1)",
      "local tSecs = (t1 and t1.value) and math.floor(math.abs(t1.value)) or 0",
      'local tStr = string.format("%d:%02d", math.floor(tSecs / 60), tSecs % 60)',
      "lcd.drawFilledRectangle(308, 64, 148, 88, DARKGREY)",
      "lcd.drawRectangle(308, 64, 148, 88, GREY)",
      'lcd.drawText(320, 72, "TIMER", SMLSIZE + GREY)',
      "lcd.drawText(320, 96, tStr, DBLSIZE + WHITE)",
    ],
  },
  {
    id: "quad-link-bar",
    label: "Link bar",
    shortLabel: "LQ",
    description: "Single full-width link quality bar",
    family: "betaflight-quad",
    protocol: "any",
    category: "strip",
    requiredSensors: ["RQLY"],
    optionalSensors: [],
    telemetryNotes: ["Minimal board link strip."],
    createSrcBindings: {
      rqly: "RQLY",
    },
    srcSlotLabels: {
      rqly: "Link quality",
    },
    defaultBounds: { x: 12, y: 200, w: 456, h: 30 },
    refreshLines: [
      "local rqly = telem(widget.src.rqly)",
      'lcd.drawText(12, 184, "LINK", SMLSIZE + GREY)',
      "lcd.drawFilledRectangle(12, 200, 456, 14, GREY)",
      "local fillW = math.floor(452 * math.max(0, math.min(100, rqly)) / 100)",
      "if fillW > 0 then lcd.drawFilledRectangle(14, 202, fillW, 10, GREEN) end",
    ],
  },
  {
    id: "quad-attitude-band",
    label: "Attitude band",
    shortLabel: "ATTB",
    description: "Compact pitch/roll band under a metric grid",
    family: "betaflight-quad",
    protocol: "any",
    category: "card",
    requiredSensors: ["Ptch", "Roll"],
    optionalSensors: ["Sats"],
    telemetryNotes: ["Sits under the dense metric grid."],
    createSrcBindings: {
      pitch: "Ptch",
      roll: "Roll",
      sats: "Sats",
    },
    srcSlotLabels: {
      pitch: "Pitch",
      roll: "Roll",
      sats: "Satellites",
    },
    defaultBounds: { x: 12, y: 216, w: 456, h: 40 },
    refreshLines: [
      "local pitch = telem(widget.src.pitch)",
      "local roll = telem(widget.src.roll)",
      "local sats = telem(widget.src.sats)",
      'local pitchStr = string.format("P %.0f", pitch)',
      'local rollStr = string.format("R %.0f", roll)',
      'local satsLine = "Sats " .. tostring(sats)',
      "lcd.drawFilledRectangle(12, 216, 456, 40, DARKGREY)",
      "lcd.drawRectangle(12, 216, 456, 40, GREY)",
      'lcd.drawText(20, 228, "ATTITUDE", SMLSIZE + GREY)',
      "lcd.drawText(112, 226, pitchStr, MIDSIZE + WHITE)",
      "lcd.drawText(232, 226, rollStr, MIDSIZE + WHITE)",
      "lcd.drawText(360, 228, satsLine, SMLSIZE + BLUE)",
    ],
  },
];

export function listBetaflightQuadPrefabIds(): string[] {
  return BETAFLIGHT_QUAD_PREFABS.map((p) => p.id);
}

/** Whoop overview board order. */
export const WHOOP_LAYOUT_ORDER = [
  "quad-armed-banner",
  "quad-link-batt-bars",
  "quad-voltage-hero",
  "quad-attitude-card",
  "quad-capacity-chip",
  "quad-mode-footer",
] as const;

/** Freestyle / FPV overview board order. */
export const FREESTYLE_LAYOUT_ORDER = [
  "quad-topbar",
  "quad-timer-hero",
  "quad-power-strip",
  "quad-gps-row",
  "quad-mode-footer",
] as const;

/** Minimal voltage-first board order. */
export const MINIMAL_QUAD_LAYOUT_ORDER = [
  "quad-topbar",
  "quad-voltage-minimal",
  "quad-timer-card",
  "quad-link-bar",
  "quad-mode-footer",
] as const;

/** Dense CRSF / power-user grid order. */
export const DENSE_CRSF_LAYOUT_ORDER = [
  "quad-topbar",
  "quad-metric-grid",
  "quad-attitude-band",
  "quad-mode-footer",
] as const;
