---@meta edgetx

--- AUTO-GENERATED BY edgetx-lua-gen (https://github.com/JeffreyChix/edgetx-lua-gen) — DO NOT EDIT MANUALLY.
--- EdgeTX Lua API stubs for lua-language-server (LuaLS)
--- All EdgeTX constants (347 total)

-- ── general constants ───────────────────────────────────────────

---@type integer
EVT_PAGE_FIRST = 0

--- MENU key long press
---@type integer
EVT_PAGE_LONG = 0

---@type integer
EVT_PAGE_REPT = 0

--- PAGE key release
---@type integer
EVT_PAGE_BREAK = 0

---@type integer
EVT_MENU_FIRST = 0

---@type integer
EVT_MENU_LONG = 0

---@type integer
EVT_MENU_REPT = 0

--- MENU key release
---@type integer
EVT_MENU_BREAK = 0

---@type integer
EVT_ENTER_FIRST = 0

--- ENT key long press
---@type integer
EVT_ENTER_LONG = 0

---@type integer
EVT_ENTER_REPT = 0

--- ENT key release
---@type integer
EVT_ENTER_BREAK = 0

---@type integer
EVT_EXIT_FIRST = 0

---@type integer
EVT_EXIT_LONG = 0

---@type integer
EVT_EXIT_REPT = 0

--- EXIT key release
---@type integer
EVT_EXIT_BREAK = 0

--- + key press
---@type integer
EVT_PLUS_FIRST = 0

---@type integer
EVT_PLUS_LONG = 0

--- + key repeat
---@type integer
EVT_PLUS_REPT = 0

--- + key release
---@type integer
EVT_PLUS_BREAK = 0

--- - key press
---@type integer
EVT_MINUS_FIRST = 0

---@type integer
EVT_MINUS_LONG = 0

--- - key repeat
---@type integer
EVT_MINUS_REPT = 0

--- - key release
---@type integer
EVT_MINUS_BREAK = 0

--- rotary encoder rotated left
---@type integer
EVT_ROT_LEFT = 0

--- rotary encoder rotated right
---@type integer
EVT_ROT_RIGHT = 0

---@type integer
EVT_UP_FIRST = 0

---@type integer
EVT_UP_LONG = 0

---@type integer
EVT_UP_REPT = 0

---@type integer
EVT_UP_BREAK = 0

---@type integer
EVT_DOWN_FIRST = 0

---@type integer
EVT_DOWN_LONG = 0

---@type integer
EVT_DOWN_REPT = 0

---@type integer
EVT_DOWN_BREAK = 0

---@type integer
EVT_RIGHT_FIRST = 0

---@type integer
EVT_RIGHT_LONG = 0

---@type integer
EVT_RIGHT_REPT = 0

---@type integer
EVT_RIGHT_BREAK = 0

---@type integer
EVT_LEFT_FIRST = 0

---@type integer
EVT_LEFT_LONG = 0

---@type integer
EVT_LEFT_REPT = 0

---@type integer
EVT_LEFT_BREAK = 0

---@type integer
EVT_SHIFT_FIRST = 0

---@type integer
EVT_SHIFT_LONG = 0

---@type integer
EVT_SHIFT_REPT = 0

---@type integer
EVT_SHIFT_BREAK = 0

---@type integer
EVT_PAGEUP_FIRST = 0

---@type integer
EVT_PAGEUP_LONG = 0

---@type integer
EVT_PAGEUP_REPT = 0

---@type integer
EVT_PAGEUP_BREAK = 0

---@type integer
EVT_PAGEDN_FIRST = 0

---@type integer
EVT_PAGEDN_LONG = 0

---@type integer
EVT_PAGEDN_REPT = 0

---@type integer
EVT_PAGEDN_BREAK = 0

---@type integer
EVT_SYS_FIRST = 0

---@type integer
EVT_SYS_LONG = 0

---@type integer
EVT_SYS_REPT = 0

---@type integer
EVT_SYS_BREAK = 0

---@type integer
EVT_MODEL_FIRST = 0

---@type integer
EVT_MODEL_LONG = 0

---@type integer
EVT_MODEL_REPT = 0

---@type integer
EVT_MODEL_BREAK = 0

---@type integer
EVT_TELEM_FIRST = 0

---@type integer
EVT_TELEM_LONG = 0

---@type integer
EVT_TELEM_REPT = 0

---@type integer
EVT_TELEM_BREAK = 0

--- When the finger touches down on the screen
---@type integer
EVT_TOUCH_FIRST = 0

--- If the finger leaves the screen without tap or slide
---@type integer
EVT_TOUCH_BREAK = 0

--- Repeats while the finger is sliding on the screen
---@type integer
EVT_TOUCH_SLIDE = 0

--- If the finger leaves the screen after a quick tap
---@type integer
EVT_TOUCH_TAP = 0

---@type integer
TINSIZE = 0

--- shadow font  2.3  Only color displays
---@type integer
SHADOWED = 0

--- Displays a color picker, returns a color flag value
---@type integer
COLOR = 0

--- Displays a toggle/checkbox, value toggles between 0 and 1
---@type integer
BOOL = 0

--- Text input option, limited to 8 characters in 2.10 or earlier, 12 characters in 2.11.
---@type integer
STRING = 0

--- -> COLOR_THEME_SECONDARY1
---@type integer
TEXT_COLOR = 0

--- -> COLOR_THEME_SECONDARY3
---@type integer
TEXT_BGCOLOR = 0

--- -> COLOR_THEME_PRIMARY2
---@type integer
TEXT_INVERTED_COLOR = 0

--- -> COLOR_THEME_FOCUS
---@type integer
TEXT_INVERTED_BGCOLOR = 0

--- -> COLOR_THEME_PRIMARY3
---@type integer
LINE_COLOR = 0

--- -> COLOR_THEME_SECONDARY3
---@type integer
SCROLLBOX_COLOR = 0

--- -> COLOR_THEME_SECONDARY1
---@type integer
MENU_TITLE_BGCOLOR = 0

--- -> COLOR_THEME_PRIMARY2
---@type integer
MENU_TITLE_COLOR = 0

--- -> COLOR_THEME_PRIMARY3
---@type integer
MENU_TITLE_DISABLE_COLOR = 0

--- -> COLOR_THEME_SECONDARY1
---@type integer
HEADER_COLOR = 0

--- -> COLOR_THEME_WARNING
---@type integer
ALARM_COLOR = 0

--- -> COLOR_THEME_WARNING
---@type integer
WARNING_COLOR = 0

--- -> COLOR_THEME_DISABLED
---@type integer
TEXT_DISABLE_COLOR = 0

--- -> COLOR_THEME_SECONDARY2
---@type integer
CURVE_AXIS_COLOR = 0

--- -> COLOR_THEME_SECONDARY1
---@type integer
CURVE_COLOR = 0

--- -> COLOR_THEME_WARNING
---@type integer
CURVE_CURSOR_COLOR = 0

--- -> COLOR_THEME_SECONDARY1
---@type integer
TITLE_BGCOLOR = 0

--- -> COLOR_THEME_FOCUS
---@type integer
TRIM_BGCOLOR = 0

--- -> COLOR_THEME_PRIMARY1
---@type integer
TRIM_SHADOW_COLOR = 0

--- -> COLOR_THEME_FOCUS
---@type integer
HEADER_BGCOLOR = 0

--- -> COLOR_THEME_SECONDARY1
---@type integer
HEADER_ICON_BGCOLOR = 0

--- -> COLOR_THEME_FOCUS
---@type integer
HEADER_CURRENT_BGCOLOR = 0

--- -> COLOR_THEME_PRIMARY2
---@type integer
MAINVIEW_PANES_COLOR = 0

--- -> COLOR_THEME_SECONDARY1
---@type integer
MAINVIEW_GRAPHICS_COLOR = 0

--- -> COLOR_THEME_PRIMARY1
---@type integer
OVERLAY_COLOR = 0

--- -> COLOR_THEME_SECONDARY1
---@type integer
BARGRAPH1_COLOR = 0

--- -> COLOR_THEME_SECONDARY2
---@type integer
BARGRAPH2_COLOR = 0

--- -> COLOR_THEME_SECONDARY3
---@type integer
BARGRAPH_BGCOLOR = 0

--- These are the theme colors plus , and they can be changed with the function lcd.setColor(color_index, color). Please note: if an indexed color is changed, then it changes everywhere that it is used. For the theme colors, this is not only in other widgets, but everywhere throughout the radio's user interface!
---@type integer
CUSTOM_COLOR = 0

---@type integer
MENU_HEADER_HEIGHT = 0

--- WHITE | RGB: rgb(255, 255, 255) | Is Light: true | Is Dark: false
---@type integer
WHITE = 0

--- GREY | RGB: rgb(128, 128, 128) | Is Light: true | Is Dark: false
---@type integer
GREY = 0

--- DARKGREY | RGB: rgb(169, 169, 169) | Is Light: true | Is Dark: false
---@type integer
DARKGREY = 0

--- BLACK | RGB: rgb(0, 0, 0) | Is Light: false | Is Dark: true
---@type integer
BLACK = 0

--- YELLOW | RGB: rgb(255, 255, 0) | Is Light: true | Is Dark: false
---@type integer
YELLOW = 0

--- BLUE | RGB: rgb(0, 0, 255) | Is Light: false | Is Dark: true
---@type integer
BLUE = 0

--- LIGHTGREY | RGB: rgb(211, 211, 211) | Is Light: true | Is Dark: false
---@type integer
LIGHTGREY = 0

---@type integer
RED = 0

--- DARKRED | RGB: rgb(139, 0, 0) | Is Light: false | Is Dark: true
---@type integer
DARKRED = 0

---@type integer
FIXEDWIDTH = 0

---@type integer
FILL_WHITE = 0

--- grey fill  2.3
---@type integer
GREY_DEFAULT = 0

---@type integer
FULLSCALE = 0

--- jumbo font  2.3
---@type integer
XXLSIZE = 0

--- double size font  2.3
---@type integer
DBLSIZE = 0

--- mid sized font  2.3
---@type integer
MIDSIZE = 0

--- small font  2.3
---@type integer
SMLSIZE = 0

--- inverted display  2.3
---@type integer
INVERS = 0

--- bold font  2.3  Only color displays. This is a font size on its own - cannot be combined with other font size flags.
---@type integer
BOLD = 0

--- blinking text  2.3
---@type integer
BLINK = 0

--- right justify  2.3
---@type integer
RIGHT = 0

--- left justify  2.3  Default for most functions not related to bitmaps
---@type integer
LEFT = 0

--- center justify  2.3  Only color displays
---@type integer
CENTER = 0

--- single decimal place  2.3  display with one decimal place (number 386 is displayed as 38.6)
---@type integer
PREC1 = 0

--- two decimal places  2.3  display with one decimal place (number 386 is displayed as 3.86)
---@type integer
PREC2 = 0

--- Numerical input option, can specify default, min and max value
---@type integer
VALUE = 0

--- Choice option, lets you pick from available sources (i.e. sticks, switches, LS)
---@type integer
SOURCE = 0

---@type integer
REPLACE = 0

---@type integer
MIXSRC_MAX = 0

---@type integer
MIXSRC_FIRST_INPUT = 0

---@type integer
MIXSRC_SA = 0

---@type integer
MIXSRC_SB = 0

---@type integer
MIXSRC_SC = 0

---@type integer
MIXSRC_SD = 0

---@type integer
MIXSRC_SE = 0

---@type integer
MIXSRC_SG = 0

---@type integer
MIXSRC_SF = 0

---@type integer
MIXSRC_SH = 0

---@type integer
MIXSRC_CH1 = 0

---@type integer
SWSRC_LAST = 0

---@type integer
MAX_SENSORS = 0

--- for FIELDS navigation
---@type integer
EVT_VIRTUAL_PREV = 0

--- for FIELDS navigation
---@type integer
EVT_VIRTUAL_NEXT = 0

--- for VALUES navigation
---@type integer
EVT_VIRTUAL_DEC = 0

--- for VALUES navigation
---@type integer
EVT_VIRTUAL_INC = 0

---@type integer
ROTENC_LOWSPEED = 0

---@type integer
ROTENC_MIDSPEED = 0

---@type integer
ROTENC_HIGHSPEED = 0

--- for FIELDS navigation
---@type integer
EVT_VIRTUAL_PREV_REPT = 0

--- for FIELDS navigation
---@type integer
EVT_VIRTUAL_NEXT_REPT = 0

--- for VALUES navigation
---@type integer
EVT_VIRTUAL_DEC_REPT = 0

--- for VALUES navigation
---@type integer
EVT_VIRTUAL_INC_REPT = 0

--- for PAGE navigation
---@type integer
EVT_VIRTUAL_PREV_PAGE = 0

--- for PAGE navigation
---@type integer
EVT_VIRTUAL_NEXT_PAGE = 0

---@type integer
EVT_VIRTUAL_MENU = 0

---@type integer
EVT_VIRTUAL_MENU_LONG = 0

---@type integer
EVT_VIRTUAL_ENTER = 0

---@type integer
EVT_VIRTUAL_ENTER_LONG = 0

---@type integer
EVT_VIRTUAL_EXIT = 0

---@type integer
EVT_RTN_FIRST = 0

--- pixels will be black  2.3
---@type integer
FORCE = 0

--- pixels will be white  2.3
---@type integer
ERASE = 0

---@type integer
ROUND = 0

--- lines will appear soild  2.3
---@type integer
SOLID = 0

--- lines will appear dotted  2.3
---@type integer
DOTTED = 0

--- width in pixels
---@type integer
LCD_W = 0

--- height in pixels
---@type integer
LCD_H = 0

---@type integer
PLAY_NOW = 0

---@type integer
PLAY_BACKGROUND = 0

--- display hours  2.3  Only for lcd/drawTimer
---@type integer
TIMEHOUR = 0

--- Raw unit (no unit)
---@type integer
UNIT_RAW = 0

--- Volts
---@type integer
UNIT_VOLTS = 0

--- Amps
---@type integer
UNIT_AMPS = 0

--- Milliamps
---@type integer
UNIT_MILLIAMPS = 0

--- Knots
---@type integer
UNIT_KTS = 0

--- Meters per Second
---@type integer
UNIT_METERS_PER_SECOND = 0

--- Feet per Second
---@type integer
UNIT_FEET_PER_SECOND = 0

--- Kilometers per Hour
---@type integer
UNIT_KMH = 0

--- Miles per Hour
---@type integer
UNIT_MPH = 0

--- Meters
---@type integer
UNIT_METERS = 0

---@type integer
UNIT_KM = 0

--- Feet
---@type integer
UNIT_FEET = 0

--- Degrees Celsius
---@type integer
UNIT_CELSIUS = 0

--- Degrees Fahrenheit
---@type integer
UNIT_FAHRENHEIT = 0

--- Percent
---@type integer
UNIT_PERCENT = 0

--- Milliamp Hour
---@type integer
UNIT_MAH = 0

--- Watts
---@type integer
UNIT_WATTS = 0

--- Milliwatts
---@type integer
UNIT_MILLIWATTS = 0

--- dB
---@type integer
UNIT_DB = 0

--- RPM
---@type integer
UNIT_RPMS = 0

--- G
---@type integer
UNIT_G = 0

--- Degrees
---@type integer
UNIT_DEGREE = 0

--- Radians
---@type integer
UNIT_RADIANS = 0

--- Milliliters
---@type integer
UNIT_MILLILITERS = 0

--- Fluid Ounces
---@type integer
UNIT_FLOZ = 0

--- Ml per minute
---@type integer
UNIT_MILLILITERS_PER_MINUTE = 0

---@type integer
UNIT_HERTZ = 0

---@type integer
UNIT_MS = 0

---@type integer
UNIT_US = 0

--- Hours
---@type integer
UNIT_HOURS = 0

--- Minutes
---@type integer
UNIT_MINUTES = 0

--- Seconds
---@type integer
UNIT_SECONDS = 0

--- Virtual unit
---@type integer
UNIT_CELLS = 0

--- Virtual unit
---@type integer
UNIT_DATETIME = 0

--- Virtual unit
---@type integer
UNIT_GPS = 0

--- Virtual unit
---@type integer
UNIT_BITFIELD = 0

--- Virtual unit
---@type integer
UNIT_TEXT = 0

---@type integer
BATTERY_CHARGE_COLOR = 0

---@type integer
CHECKBOX_COLOR = 0

---@type integer
DEFAULT_BGCOLOR = 0

---@type integer
DEFAULT_COLOR = 0

---@type integer
DISABLE_COLOR = 0

---@type integer
FOCUS_BGCOLOR = 0

---@type integer
FOCUS_COLOR = 0

---@type integer
HIGHLIGHT_COLOR = 0

---@type integer
MENU_BGCOLOR = 0

---@type integer
MENU_COLOR = 0

---@type integer
MENU_HIGHLIGHT_BGCOLOR = 0

---@type integer
MENU_HIGHLIGHT_COLOR = 0

---@type integer
MENU_LINE_COLOR = 0

---@type integer
SCROLLBAR_COLOR = 0

---@type integer
TABLE_BGCOLOR = 0

---@type integer
TABLE_HEADER_BGCOLOR = 0

---@type integer
TEXT_STATUSBAR_COLOR = 0

--- center vertically  2.5.0  Only color displays
---@type integer
VCENTER = 0

--- Theme color. They can be changed with the function lcd.setColor(color_index, color). Please note: if an indexed color is changed, then it changes everywhere that it is used. For the theme colors, this is not only in other widgets, but everywhere throughout the radio's user interface!
---@type integer
COLOR_THEME_PRIMARY1 = 0

--- Theme color. They can be changed with the function lcd.setColor(color_index, color). Please note: if an indexed color is changed, then it changes everywhere that it is used. For the theme colors, this is not only in other widgets, but everywhere throughout the radio's user interface!
---@type integer
COLOR_THEME_PRIMARY2 = 0

--- Theme color. They can be changed with the function lcd.setColor(color_index, color). Please note: if an indexed color is changed, then it changes everywhere that it is used. For the theme colors, this is not only in other widgets, but everywhere throughout the radio's user interface!
---@type integer
COLOR_THEME_PRIMARY3 = 0

--- Theme color. They can be changed with the function lcd.setColor(color_index, color). Please note: if an indexed color is changed, then it changes everywhere that it is used. For the theme colors, this is not only in other widgets, but everywhere throughout the radio's user interface!
---@type integer
COLOR_THEME_SECONDARY1 = 0

--- Theme color. They can be changed with the function lcd.setColor(color_index, color). Please note: if an indexed color is changed, then it changes everywhere that it is used. For the theme colors, this is not only in other widgets, but everywhere throughout the radio's user interface!
---@type integer
COLOR_THEME_SECONDARY2 = 0

--- Theme color. They can be changed with the function lcd.setColor(color_index, color). Please note: if an indexed color is changed, then it changes everywhere that it is used. For the theme colors, this is not only in other widgets, but everywhere throughout the radio's user interface!
---@type integer
COLOR_THEME_SECONDARY3 = 0

--- Theme color. They can be changed with the function lcd.setColor(color_index, color). Please note: if an indexed color is changed, then it changes everywhere that it is used. For the theme colors, this is not only in other widgets, but everywhere throughout the radio's user interface!
---@type integer
COLOR_THEME_FOCUS = 0

--- Theme color. They can be changed with the function lcd.setColor(color_index, color). Please note: if an indexed color is changed, then it changes everywhere that it is used. For the theme colors, this is not only in other widgets, but everywhere throughout the radio's user interface!
---@type integer
COLOR_THEME_EDIT = 0

--- Theme color. They can be changed with the function lcd.setColor(color_index, color). Please note: if an indexed color is changed, then it changes everywhere that it is used. For the theme colors, this is not only in other widgets, but everywhere throughout the radio's user interface!
---@type integer
COLOR_THEME_ACTIVE = 0

--- Theme color. They can be changed with the function lcd.setColor(color_index, color). Please note: if an indexed color is changed, then it changes everywhere that it is used. For the theme colors, this is not only in other widgets, but everywhere throughout the radio's user interface!
---@type integer
COLOR_THEME_WARNING = 0

--- Theme color. They can be changed with the function lcd.setColor(color_index, color). Please note: if an indexed color is changed, then it changes everywhere that it is used. For the theme colors, this is not only in other widgets, but everywhere throughout the radio's user interface!
---@type integer
COLOR_THEME_DISABLED = 0

---@type integer
LIGHTWHITE = 0

--- DARKBLUE | RGB: rgb(0, 0, 139) | Is Light: false | Is Dark: true
---@type integer
DARKBLUE = 0

--- GREEN | RGB: rgb(0, 128, 0) | Is Light: false | Is Dark: true
---@type integer
GREEN = 0

--- DARKGREEN | RGB: rgb(0, 100, 0) | Is Light: false | Is Dark: true
---@type integer
DARKGREEN = 0

---@type integer
LIGHTBROWN = 0

---@type integer
DARKBROWN = 0

---@type integer
BRIGHTGREEN = 0

--- ORANGE | RGB: rgb(255, 165, 0) | Is Light: true | Is Dark: false
---@type integer
ORANGE = 0

---@type integer
AM_RDO = 0

---@type integer
AM_HID = 0

---@type integer
AM_SYS = 0

---@type integer
AM_DIR = 0

---@type integer
AM_ARC = 0

---@type integer
FUNC_DISABLE_TOUCH = 0

---@type integer
SWITCH_COUNT = 0

--- -
---@type integer
LS_FUNC_NONE = 0

--- a = x
---@type integer
LS_FUNC_VEQUAL = 0

--- a \~ x
---@type integer
LS_FUNC_VALMOSTEQUAL = 0

--- a > x
---@type integer
LS_FUNC_VPOS = 0

--- a < x
---@type integer
LS_FUNC_VNEG = 0

---@type integer
LS_FUNC_RANGE = 0

--- a > \|x\|
---@type integer
LS_FUNC_APOS = 0

--- a < \|x\|
---@type integer
LS_FUNC_ANEG = 0

--- AND
---@type integer
LS_FUNC_AND = 0

--- OR
---@type integer
LS_FUNC_OR = 0

--- XOR
---@type integer
LS_FUNC_XOR = 0

--- Edge
---@type integer
LS_FUNC_EDGE = 0

--- a = b
---@type integer
LS_FUNC_EQUAL = 0

--- a > b
---@type integer
LS_FUNC_GREATER = 0

--- a < b
---@type integer
LS_FUNC_LESS = 0

--- ∆ ≥ x
---@type integer
LS_FUNC_DIFFEGREATER = 0

--- \|∆\| ≥ x
---@type integer
LS_FUNC_ADIFFEGREATER = 0

--- Timer
---@type integer
LS_FUNC_TIMER = 0

--- Sticky
---@type integer
LS_FUNC_STICKY = 0

---@type integer
FUNC_OVERRIDE_CHANNEL = 0

---@type integer
FUNC_TRAINER = 0

---@type integer
FUNC_INSTANT_TRIM = 0

---@type integer
FUNC_RESET = 0

---@type integer
FUNC_SET_TIMER = 0

---@type integer
FUNC_ADJUST_GVAR = 0

---@type integer
FUNC_VOLUME = 0

---@type integer
FUNC_SET_FAILSAFE = 0

---@type integer
FUNC_RANGECHECK = 0

---@type integer
FUNC_BIND = 0

---@type integer
FUNC_PLAY_SOUND = 0

---@type integer
FUNC_PLAY_TRACK = 0

---@type integer
FUNC_PLAY_VALUE = 0

---@type integer
FUNC_PLAY_SCRIPT = 0

---@type integer
FUNC_BACKGND_MUSIC = 0

---@type integer
FUNC_BACKGND_MUSIC_PAUSE = 0

---@type integer
FUNC_VARIO = 0

---@type integer
FUNC_HAPTIC = 0

---@type integer
FUNC_LOGS = 0

---@type integer
FUNC_BACKLIGHT = 0

---@type integer
FUNC_SCREENSHOT = 0

---@type integer
FUNC_RACING_MODE = 0

---@type integer
CHAR_RIGHT = 0

---@type integer
CHAR_LEFT = 0

---@type integer
CHAR_UP = 0

---@type integer
CHAR_DOWN = 0

---@type integer
CHAR_DELTA = 0

---@type integer
CHAR_STICK = 0

---@type integer
CHAR_POT = 0

---@type integer
CHAR_SLIDER = 0

---@type integer
CHAR_SWITCH = 0

---@type integer
CHAR_TRIM = 0

---@type integer
CHAR_INPUT = 0

---@type integer
CHAR_FUNCTION = 0

---@type integer
CHAR_CYC = 0

---@type integer
CHAR_TRAINER = 0

---@type integer
CHAR_CHANNEL = 0

---@type integer
CHAR_TELEMETRY = 0

---@type integer
CHAR_LUA = 0

---@type integer
FUNC_SET_SCREEN = 0

--- Choice option, lets you pick from available timers
---@type integer
TIMER = 0

--- Choice option, lets you pick from the available text sizes (i.e. small, large)
---@type integer
TEXT_SIZE = 0

---@type integer
MAX_OUTPUT_CHANNELS = 0

---@type integer
LIMIT_EXT_PERCENT = 0

---@type integer
LIMIT_STD_PERCENT = 0

--- Choice option, lets you pick from available alignment options (i.e. left, center, right)
---@type integer
ALIGNMENT = 0

--- Choice option to select from available switches.
---@type integer
SWITCH = 0

---@type integer
UNIT_DBM = 0

---@type integer
MIXSRC_MIN = 0

---@type integer
LED_STRIP_LENGTH = 0

---@type integer
STDSIZE = 0

--- align to top  2.11.4  Only for color displays using the LVGL API.
---@type integer
VTOP = 0

--- align to bottom  2.11.4  Only for color displays using hte LVGL API.
---@type integer
VBOTTOM = 0

--- Select numerical value using a slider control (available in 2.11)
---@type integer
SLIDER = 0

--- Select numerical value using a custom popup list (available in 2.11)
---@type integer
CHOICE = 0

--- Select a file from SD card / internal storage (available in 2.11). Filename is limited to 12 characters maximum.
---@type integer
FILE = 0

---@type integer
FUNC_PUSH_CUST_SWITCH = 0

--- when a key is pressed a `` event is generated
---@type integer
FIRST = 0

--- if the key continues to be pressed, then after a while a `` event is generated
---@type integer
LONG = 0

--- if the key continues to be pressed, then a `` events are being generated
---@type integer
REPEAT = 0

--- when the key is released a `` event is generated
---@type integer
BREAK = 0

--- rotary encoder release
---@type integer
EVT_ROT_BREAK = 0

--- rotary encoder long press
---@type integer
EVT_ROT_LONG = 0

--- Given the large number of radios supported by OpenTX, and the large difference in keys available on those, a set of  KEYS has been defined and are mapped to best fit available hardware
---@type integer
VIRTUAL = 0

--- for PAGE navigation
---@type integer
EVT_VIRTUAL_PREVIOUS_PAGE = 0

--- for FIELDS navigation
---@type integer
EVT_VIRTUAL_PREVIOUS = 0

--- When the finger touches down on the screen
---@type integer
EVT_TOUCH___FIRST = 0

--- If the finger leaves the screen after a quick tap
---@type integer
EVT_TOUCH___TAP = 0

--- If the finger leaves the screen without tap or slide
---@type integer
EVT_TOUCH___BREAK = 0

--- Repeats while the finger is sliding on the screen
---@type integer
EVT_TOUCH___SLIDE = 0

--- slideX, SlideY                                Movement since previous  event (or start of slide)
---@type integer
SLIDE = 0

---@type integer
FUNC_RESERVE5 = 0

